# Generated by Django 4.2.4 on 2024-02-29 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=150, verbose_name='Название профессии')),
                ('img', models.ImageField(blank=True, upload_to='users/', verbose_name='Фотография')),
                ('about', models.TextField(verbose_name='Описание работы')),
                ('age', models.IntegerField(default=14, verbose_name='Возраст')),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('A', 'Любой')], default='A', max_length=1, verbose_name='Пол')),
                ('rus_passport', models.BooleanField(verbose_name='Наличие Гражданства РФ')),
                ('insurance', models.BooleanField(verbose_name='Наличие медицинской страховки')),
                ('status', models.BooleanField(default=True, verbose_name='Активна?')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Оплата труда')),
                ('date_start', models.DateTimeField(db_comment='Начальное время работы', verbose_name='Начало работы')),
                ('date_end', models.DateTimeField(db_comment='Конечное время работы', verbose_name='Конец работы')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'Service',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Никнейм')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=150, unique=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=30, unique=True, verbose_name='Номер телефона')),
                ('password', models.CharField(max_length=150, verbose_name='Пароль')),
                ('isAdmin', models.BooleanField(default=False, verbose_name='Является модератором')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'User',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(blank=True, null=True, verbose_name='Время создания')),
                ('date_formation', models.DateTimeField(blank=True, null=True, verbose_name='Время формирования')),
                ('date_finish', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалено'), ('formed', 'Сформировано'), ('completed', 'Завершено'), ('rejected', 'Отклонено')], default='draft', max_length=10, verbose_name='Статус')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_bids', to='main.user', verbose_name='Идентификатор модератора')),
                ('services', models.ManyToManyField(blank=True, db_table='ServiceBid', to='main.service', verbose_name='Услуги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bids', to='main.user', verbose_name='Идентификатор пользователя')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'Bid',
                'ordering': ['date_create'],
                'managed': True,
            },
        ),
    ]
